#!/bin/bash

# Copyright (c) 2015 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#*****************************************************
# Update SAT BINARY release to latest and greatest
#*****************************************************

SAT_BIN_PATH=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
SAT_RELEASE_SERVER="http://satt.example.com"

# $SAT_HOME --> Path to SAT-tool root folder
export SAT_HOME=$(cd $SAT_BIN_PATH/../ && pwd )

# Add bin folder into path
export PATH=$PATH:$SAT_BIN_PATH

pushd .

cd $SAT_HOME

wget -qO- $SAT_RELEASE_SERVER/releases/sat-latest.tgz | tar -xvzf-

popd
