#
# Copyright (c) 2015 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Import(['env', 'srcdirs', 'libdirs', 'installdir'])

localenv = env.Clone()

localenv.components = ['ipt-parser', 'common', 'sideband-parser', 'disassembler']

localenv.component_srcdirs = [ srcdirs[x] for x in localenv.components ]
localenv.component_libdirs = [ libdirs[x] for x in localenv.components ]


localenv.StaticLibrary('sat-common',
                  ['sat-log.cpp', 'sat-getline.cpp', 'sat-md5.cpp', 'md5.c'])

localenv.Program(['sat-path-map.cpp',
                  'sat-local-path-mapper.cpp',
                  'sat-filesystem.cpp'],
                  LIBS = ['sat-common', 'sat-disassembler'],
                  LIBPATH = localenv.component_libdirs)

localenv.Install(installdir, [
                               'sat-path-map'
                             ])