#
# Copyright (c) 2015 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Import(['env', 'srcdirs', 'libdirs', 'installdir'])

localenv = env.Clone()

localenv.components = ['common', 'sideband-parser']

localenv.component_libdirs = [ libdirs[x] for x in localenv.components ]
localenv.component_srcdirs = [ srcdirs[x] for x in localenv.components ]

localenv.component_srcdirs = localenv.component_srcdirs + ['#../../kernel-module']

localenv.Append(CPPPATH = localenv.component_srcdirs)

localenv.StaticLibrary('sat-sideband-parser', ['sat-sideband-parser.cpp'])
localenv.Program(['sat-sideband-dump.cpp'],
                 LIBS = ['sat-sideband-parser'],
                 LIBPATH = localenv.component_libdirs)
localenv.Install(installdir, [
                               'sat-sideband-dump'
                             ])
