#
# Copyright (c) 2015 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import commands

flags = ARGUMENTS.get('flags', '-O3') + ' '

env = Environment(CCFLAGS   = flags + '-std=c++0x -Wall',
                  CPPPATH   = ['../common',
                               '../../sideband-parser/src',
                               '../../../kernel-module',
                               '../../rtit-parser/src',
                               '../../disassembler/src'],
                  LINKFLAGS = flags + '-static')

env.Program(['sat-rtit-model.cpp',
             'sat-sideband-model.cpp',
             'sat-scheduling-heuristics.cpp',
             'sat-rtit-instruction.cpp',
             'sat-system-map.cpp',
             'sat-call-stack.cpp',
             'sat-tid.cpp',
             'sat-demangle.cpp',
             'sat-path-mapper.cpp'
             'sat-filesystem.o'],
             LIBS = ['sat-common',
                     'sat-sideband-parser',
                     'sat-rtit-parser',
                     'sat-disassembler',
                     'capstone'],
             LIBPATH = ['../../common/src',
                        '../../sideband-parser/src',
                        '../../rtit-parser/src',
                        '../../disassembler/src'])
env.Program(['sat-dump-scheduling-heuristics.cpp',
             'sat-sideband-model.o',
             'sat-scheduling-heuristics.o',
             'sat-tid.o'],
             LIBS = ['sat-common',
                     'sat-sideband-parser',
                     'sat-rtit-parser',
                     'sat-disassembler'],
             LIBPATH = ['../../common/src',
                        '../../sideband-parser/src',
                        '../../rtit-parser/src'])
