#
# Copyright (c) 2015 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

flags = ARGUMENTS.get('flags', '-O3') + ' '

env = Environment(CCFLAGS   = flags + '-std=c++0x -Wall',
                  CPPPATH   = ['../../common/src'],
                  LINKFLAGS = flags + '-static')

env.StaticLibrary('sat-rtit-parser', ['sat-rtit-parser.cpp',
                                      'sat-rtit-tsc-heuristics.cpp',
                                      'sat-rtit-tsc.cpp',
                                      'sat-rtit-overflow-heuristics.cpp'])
env.Program(['sat-rtit-dump.cpp'], LIBS=['sat-rtit-parser'], LIBPATH='.')
env.Program(['sat-rtit-dump-time.cpp'], LIBS=['sat-rtit-parser'], LIBPATH='.')
env.Program(['sat-rtit-stats.cpp'], LIBS=['sat-rtit-parser'], LIBPATH='.')
env.Program(['sat-dump-overflow-times.cpp'], LIBS=['sat-rtit-parser'], LIBPATH='.')
env.Program(['sat-rtit-dump-tscs.cpp'], LIBS=['sat-rtit-parser'], LIBPATH='.')
env.Program(['sat-rtit-dump-tsc-heuristics.cpp'], LIBS=['sat-rtit-parser'], LIBPATH='.')
