#
# Copyright (c) 2015 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import commands

flags = ARGUMENTS.get('flags', '-O3') + ' '

env = Environment(CCFLAGS   = flags + '-std=c++0x -Wall',
                  CPPPATH   = ['../../common/src'],
                  LINKFLAGS = flags + '')

env.StaticLibrary('sat-disassembler',
                  ['sat-disassembler.cpp', 'sat-mmapped.cpp', 'sat-elf.cpp'],
                  LIBS = ['sat-common'],
                  LIBPATH = ['../../common/src'])

env.Program(['sat-disassembler-dump.cpp'],
            LIBS=['sat-disassembler',
                  'sat-common',
                  File('/usr/lib/libcapstone.a'),
                  File('/usr/lib/libbfd.a'),
                  File(commands.getoutput('g++ -print-file-name=libelf.a')),
                  'iberty',
                  'z',
                  'dl'],
            LIBPATH=['.', '../../common/src'])

env.Program(['sat-elf-dump.cpp'],
            LIBS=['sat-disassembler', 'sat-common', 'elf'],
            LIBPATH=['.', '../../common/src'])
