#
# Copyright (c) 2015 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import commands

Import(['env', 'srcdirs', 'libdirs', 'installdir'])

components = ['common', 'disassembler']

component_srcdirs = [ srcdirs[x] for x in components ]
component_libdirs = [ libdirs[x] for x in components ]

localenv = env.Clone()
localenv.Append(CPPPATH = component_srcdirs)

localenv.StaticLibrary('sat-disassembler',
                       ['sat-disassembler-capstone.cpp',
                        'sat-mmapped.cpp',
                        'sat-elf.cpp',
                        'sat-oat.cpp',
                        'sat-oat-header.cpp',
                        'sat-demangle.cpp',
                        'sat-elfio-hack.cpp'],
                       LIBS = ['sat-common', 'capstone'],
                       LIBPATH = component_libdirs)

localenv.Program(['sat-symbol-dump.cpp'],
                 LIBS=['sat-disassembler',
                       'sat-common', 'capstone'],
                 LIBPATH=component_libdirs)
localenv.Program(['sat-disassembler-dump.cpp'],
                 LIBS=['sat-disassembler',
                       'sat-common',
                       'capstone',
                       'iberty',
                       'z',
                       'dl'],
                 LIBPATH=component_libdirs)
localenv.Program(['sat-elf-dump.cpp'],
            LIBS=['sat-disassembler', 'sat-common', 'capstone'],
            LIBPATH=component_libdirs)

localenv.Install(installdir, [
                               'sat-symbol-dump',
                               'sat-disassembler-dump',
                               'sat-elf-dump'
                             ])


#LIBPATH=['.', '../../common/src'])
